# see https://symfony.com/doc/current/reference/configuration/framework.html
framework:
    secret: '%env(APP_SECRET)%'
    session: true
    php_errors:
        log: true

    http_client:
        scoped_clients:
            openrouter.client:
                base_uri: 'https://openrouter.ai/api/v1/'
                headers:
                    Authorization: 'Bearer %env(OPENROUTER_API_KEY)%'
                max_duration: '%env(float:OPENROUTER_TIMEOUT)%'
