nelmio_api_doc:
    use_validation_groups: true
    documentation:
        info:
            title: Comment API
            description: Collecte et modération des commentaires publiés sur les marques du groupe.
            version: '%env(resolve:REVISION)%'
        servers:
            -   url: http://localhost:8080
                description: Local
    areas:
        Health:
            path_patterns:
                - ^/health

        default:
            path_patterns:
                - ^/(?!_(error|wdt|profiler)).*
