parameters:
    env(APP_ENV): ''
    env(REVISION): '1.0.0'
    env(APP_SECRET): ''
    env(DATABASE_URL): ''

services:
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    _instanceof:
        Symfony\Component\Serializer\SerializerAwareInterface:
            calls:
                - [ 'setSerializer', [ ] ]

    SudOuest\Comment\:
        resource: '../src/'

when@test:
    services:
        SudOuest\Comment\Tests\Support\Moderation\StubModerator: ~
        SudOuest\Comment\Domain\Moderation\Moderator: '@SudOuest\Comment\Tests\Support\Moderation\StubModerator'
